name: "CI-01:Build&Test"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      skip_tests:
        description: 'Skip tests (faster builds)'
        required: false
        default: 'false'
        type: choice
        options:
          - 'true'
          - 'false'

env:
  CARGO_TERM_COLOR: always
  FREETYPE_SYS_USE_PKG_CONFIG: 1
  RUST_BACKTRACE: 1
  # Projekt-MS RUNTIME-Vorgabe (MSRV)
  RUST_TOOLCHAIN: stable

jobs:
  # Code quality checks
  quality:
    name: Code Quality (Format & Lint)
    runs-on: ubuntu-latest
    permissions:
      contents: read
    
    steps:
    - name: Configure Git
      run: git config --global --add safe.directory "*"
    - uses: actions/checkout@v4

    - name: Set up Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        override: true
        components: rustfmt, clippy

    - name: Install system dependencies (Ubuntu)
      run: |
        sudo apt-get update
        sudo apt-get install -y libasound2-dev pkg-config
        bash scripts/install-ffmpeg-dev.sh

    - name: Check formatting
      run: cargo fmt --all -- --check

    - name: Run Clippy
      run: cargo clippy --workspace --all-features -- -D warnings

  # Build and test on Ubuntu with audio support
  build-and-test:
    name: Build & Test (Ubuntu with Audio)
    runs-on: ubuntu-24.04
    # Use a newer toolchain for building (resolver for dependencies that require newer Cargo)
    env:
      RUST_TOOLCHAIN: stable
    permissions:
      contents: read
        
    steps:
    - name: Configure Git
      run: git config --global --add safe.directory "*"
    - name: Free Disk Space (Ubuntu)
      uses: jlumbroso/free-disk-space@main
      with:
        # this might remove tools that are actually needed, if set to "true" but usually safe for rust builds
        tool-cache: false
        android: true
        dotnet: true
        haskell: true
        large-packages: true
        swap-storage: true
        
    - uses: actions/checkout@v4

    - name: Set up Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        override: true
        components: rustfmt, clippy

    - name: Rust Cache
      uses: swatinem/rust-cache@v2

    - name: Install system dependencies (Ubuntu)
      run: |
        sudo apt-get update -y
        sudo apt-get install -y \
          build-essential \
          pkg-config \
          clang \
          libclang-dev \
          libfontconfig1-dev \
          libfreetype6-dev \
          libxcb1-dev \
          libxcb-render0-dev \
          libxcb-shape0-dev \
          libxcb-xfixes0-dev \
          libx11-dev \
          libavcodec-dev \
          libavformat-dev \
          libavutil-dev \
          libswscale-dev \
          libavdevice-dev \
          libavfilter-dev \
          libswresample-dev \
          ffmpeg \
          libasound2-dev
        bash scripts/install-ffmpeg-dev.sh
        # Verify installations
        pkg-config --exists fontconfig && echo "✓ Fontconfig found" || echo "✗ Fontconfig not found"
        pkg-config --exists freetype2 && echo "✓ FreeType found" || echo "✗ FreeType not found"
        pkg-config --exists alsa && echo "✓ ALSA found" || echo "✗ ALSA not found"
        pkg-config --exists libavutil && echo "✓ libavutil found" || (echo "✗ libavutil not found"; exit 1)

    # We only build RELEASE to save disk space (debug artifacts are huge)
    - name: Build & Test (Release)
      env:
        RUST_BACKTRACE: full
      run: |
        cargo build --release --verbose --all-features
        
    - name: Run tests (Release)
      if: ${{ github.event.inputs.skip_tests != 'true' }}
      env:
        RUST_BACKTRACE: full
      run: cargo test --release --workspace --verbose --all-features

    - name: Run doc tests
      if: ${{ github.event.inputs.skip_tests != 'true' }}
      run: cargo test --release --doc --verbose --all-features

    - name: Generate documentation
      run: cargo doc --no-deps --all-features

    - name: Upload artifacts (Release binary)
      uses: actions/upload-artifact@v4
      with:
        name: mapflow-ubuntu-audio-release
        path: target/release/MapFlow
        if-no-files-found: ignore

  # Build on Windows (without FFmpeg - ffmpeg-next 6.x incompatible with FFmpeg 7.x)
  build-windows:
    name: Build (Windows)
    runs-on: windows-latest
    env:
      RUST_TOOLCHAIN: stable
    permissions:
      contents: read
    
    steps:
    - name: Configure Git
      run: git config --global core.autocrlf false
    - uses: actions/checkout@v4

    - name: Set up Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        override: true
        components: rustfmt, clippy

    - name: Rust Cache
      uses: swatinem/rust-cache@v2

    - name: Build (Release, no FFmpeg)
      env:
        RUST_BACKTRACE: full
      run: |
        cargo build --release --verbose --no-default-features --features audio

    - name: Run tests (Release, no FFmpeg)
      if: ${{ github.event.inputs.skip_tests != 'true' }}
      env:
        RUST_BACKTRACE: full
      run: cargo test --release --workspace --verbose --no-default-features --features audio

    - name: Upload artifacts (Windows binary)
      uses: actions/upload-artifact@v4
      with:
        name: mapflow-windows-release
        path: target/release/MapFlow.exe
        if-no-files-found: ignore

  # Security scanning
  security:
    name: Security Audit
    runs-on: ubuntu-latest
    # use newer toolchain for security scanning/build
    env:
      RUST_TOOLCHAIN: stable
    permissions:
      security-events: write
      contents: read
      checks: write
    
    steps:
    - name: Configure Git
      run: git config --global --add safe.directory "*"
    - uses: actions/checkout@v4

    - name: Set up Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        override: true

    - name: Run cargo audit
      uses: rustsec/audit-check@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

  # Success gate for branch protection
  ci-success:
    name: CI Success Gate
    needs: [quality, build-and-test, build-windows, security]
    runs-on: ubuntu-latest
    if: always()
    permissions:
      contents: read
    
    steps:
    - name: Fail if any job failed or was cancelled
      if: always()
      run: |
        # Check results of dependent jobs and fail if any are not "success"
        # Note: build-windows is included but may have issues with FFmpeg - we log but don't fail
        if [ "${{ needs.quality.result }}" != "success" ] || [ "${{ needs.build-and-test.result }}" != "success" ] || [ "${{ needs.security.result }}" != "success" ]; then
          echo "::error::One or more required jobs failed or were cancelled."
          echo "quality: ${{ needs.quality.result }}"
          echo "build-and-test: ${{ needs.build-and-test.result }}"
          echo "build-windows: ${{ needs.build-windows.result }}"
          echo "security: ${{ needs.security.result }}"
          exit 1
        fi
        if [ "${{ needs.build-windows.result }}" != "success" ]; then
          echo "::warning::Windows build did not succeed (result: ${{ needs.build-windows.result }}), but this is not blocking."
        fi
        echo "✓ All CI checks passed successfully"
